# Generated by Django 5.2.1 on 2025-05-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_usuario_comuna_usuario_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='registroPersonal',
        ),
    ]
